%YAML:1.0
cfg_avt_0: 0.32       #UtcSetDynParam(obj, dynamicParam.occlusion_thred)
cfg_avt_1: 0.38       #UtcSetDynParam(obj, dynamicParam.retry_acq_thred)
cfg_avt_2: 0     #UtcSetUpFactor(obj, up_factor)
cfg_avt_3: 80         #UtcSetRestraint(obj, resTraint.res_distance)
cfg_avt_4: 12000      #UtcSetRestraint(obj, resTraint.res_area)
cfg_avt_5: 10         #UtcSetIntervalFrame(obj, gapframe)
cfg_avt_6: 1          #UtcSetEnhance(obj, enhEnable)
cfg_avt_7: 3.0        #UtcSetEnhfClip(obj, cliplimit)
cfg_avt_8: 1          #UtcSetPredict(obj, dictEnable)
cfg_avt_9: 25         #UtcSetMvPixel(obj, moveX)
cfg_avt_10: 20        #UtcSetMvPixel(obj, moveY)
cfg_avt_11: 15        #UtcSetMvPixel2(obj, moveX2)
cfg_avt_12: 15        #UtcSetMvPixel2(obj, moveY2)
cfg_avt_13: 650       #UtcSetSegPixelThred(obj, segPixelX)
cfg_avt_14: 400       #UtcSetSegPixelThred(obj, segPixelY)
cfg_avt_15: 0         #algOsdRect Enable
cfg_avt_16: 384       #UtcSetSalientScaler(obj, ScalerLarge)
cfg_avt_17: 192       #UtcSetSalientScaler(obj, ScalerMid)
cfg_avt_18: 128       #UtcSetSalientScaler(obj, ScalerSmall)
cfg_avt_19: 30        #UtcSetSalientScatter(obj, Scatter)
cfg_avt_20: 1.2       #UtcSetSRAcqRatio(obj, ratio)
cfg_avt_21: 1         #UtcSetBlurFilter(obj,FilterEnable)
cfg_avt_22: 1         #UtcSetBigSearch(obj, BigSecEnable)
cfg_avt_23: 100       #UtcSetSalientThred(obj,SalientThred)
cfg_avt_24: 1         #UtcSetMultScaler(obj, ScalerEnable)
cfg_avt_25: 0         #UtcSetDynamicRatio(obj, DynamicRatioEnable)
cfg_avt_26: 12        #UtcSetSRMinAcqSize(obj,acqSize.width)
cfg_avt_27: 12        #UtcSetSRMinAcqSize(mobj,acqSize.height)
cfg_avt_28: 0         #TrkAim 4:3 Enable
cfg_avt_29: 0         #UtcSetSceneMV(obj, SceneMVEnable)
cfg_avt_30: 0         #UtcSetBackTrack(obj, BackTrackEnable)
cfg_avt_31: 1         #UtcSetAveTrkPos(obj, bAveTrkPos)
cfg_avt_32: 1.0       #UtcSetDetectftau(obj, fTau)
cfg_avt_33: 400       #UtcSetDetectBuildFrms(obj, buildFrms)
cfg_avt_34: 40        #UtcSetLostFrmThred(obj, LostFrmThred)
cfg_avt_35: 0.5       #UtcSetHistMVThred(obj, histMvThred)
cfg_avt_36: 15        #UtcSetDetectFrmsThred(obj, detectFrms)
cfg_avt_37: 30        #UtcSetStillFrmsThred(obj, stillFrms)
cfg_avt_38: 0.25      #UtcSetStillPixThred(obj, stillThred)
cfg_avt_39: 0         #UtcSetKalmanFilter(obj, bKalmanFilter)
cfg_avt_40: 4.0       #UtcSetKFMVThred(obj, xMVThred,)
cfg_avt_41: 3.0       #UtcSetKFMVThred(obj, yMVThred)
cfg_avt_42: 0.5       #UtcSetKFStillThred(obj, xStillThred)
cfg_avt_43: 0.4       #UtcSetKFStillThred(obj, yStillThred)
cfg_avt_44: 0.08      #UtcSetKFSlopeThred(obj, slopeThred)
cfg_avt_45: 2.5       #UtcSetKFHistThred(obj, kalmanHistThred)
cfg_avt_46: 0.00001   #UtcSetKFCoefQR(obj, kalmanCoefQ)
cfg_avt_47: 0.0025    #UtcSetKFCoefQR(obj, kalmanCoefR)
cfg_avt_48: 0         #UtcSetSceneMVRecord(obj, bSceneMVRecord)
cfg_avt_49: 0         #move target DetectEnable
cfg_avt_50: 0         #target DetectTrkSR Enable
cfg_avt_51: 0         #UtcSetSceneEnh(obj, bEnhScene)
cfg_avt_52: 1         #UtcSetSceneEnhMacro(obj, nrxScene);
cfg_avt_53: 1         #UtcSetSceneEnhMacro(obj, nryScene);
cfg_avt_54: 10000     #lossCoastTelapseMax (ms)

