%YAML:1.0
cfg_mmt_0: 10
cfg_mmt_1: 1000
cfg_mmt_2: 20000
cfg_mmt_3: 6
cfg_mmt_4: 16
cfg_mmt_5: 1.25
cfg_mmt_6: 50
cfg_mmt_7: 1
cfg_mmt_8: 35
cfg_mmt_9: 12
cfg_mmt_10: 65
cfg_mmt_11: 3
cfg_mmt_12: 0
cfg_mmt_13: 128

